$(document).ready(function(){
	$('.toolshow').tooltip();
	$('.toolauthority').tooltip();
	$('.tooledit').tooltip();
	$('.tooldelete').tooltip();
	$('.tooladdstudents').tooltip();
	$('.tooladdteachers').tooltip();
	$('.tooladdpleasures').tooltip();
	$('.tooladdsubjects').tooltip();
	$('.tooladdscores').tooltip();
	alert("hhfhfhf");
});